In [1]:
!pip install datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.4/487.4 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 11.4 MB/s eta 0:00:00


In [3]:
from datasets import load_dataset

dataset=load_dataset('glue','cola')
dataset=dataset['train']#Just select training split for now

In [4]:
dataset

Dataset({
    features: ['sentence', 'label', 'idx'],
    num_rows: 8551
})

In [7]:
import pandas as pd
df=pd.DataFrame()
df['idx']=dataset['idx']
df['sentence']=dataset['sentence']
df['label']=dataset['label']
df.head()

,idx,sentence,label
0,0,"Our friends won't buy this analysis, let alone...",1
1,1,One more pseudo generalization and I'm giving up.,1
2,2,One more pseudo generalization or I'm giving up.,1
3,3,"The more we study verbs, the crazier they get.",1
4,4,Day by day the facts are getting murkier.,1


#Read the tokenizer


In [9]:
from transformers import AutoTokenizer

In [30]:
tokenizer=AutoTokenizer.from_pretrained('google-bert/bert-base-cased')
tokenized_data=tokenizer(dataset['sentence'],return_tensors='np',padding=True)
tokenized_data=dict(tokenized_data)

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [11]:
tokenized_data

{'input_ids': array([[ 101, 2256, 2814, ...,    0,    0,    0],
        [ 101, 2028, 2062, ...,    0,    0,    0],
        [ 101, 2028, 2062, ...,    0,    0,    0],
        ...,
        [ 101, 2009, 2003, ...,    0,    0,    0],
        [ 101, 1045, 2018, ...,    0,    0,    0],
        [ 101, 2054, 2035, ...,    0,    0,    0]]),
 'token_type_ids': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 'attention_mask': array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]])}

In [13]:
tokenized_data=tokenizer(dataset['sentence'],
                         return_tensors='np',
                         padding=True,
                         truncation=True)
tokenized_data

{'input_ids': array([[ 101, 2256, 2814, ...,    0,    0,    0],
       [ 101, 2028, 2062, ...,    0,    0,    0],
       [ 101, 2028, 2062, ...,    0,    0,    0],
       ...,
       [ 101, 2009, 2003, ...,    0,    0,    0],
       [ 101, 1045, 2018, ...,    0,    0,    0],
       [ 101, 2054, 2035, ...,    0,    0,    0]]), 'token_type_ids': array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]]), 'attention_mask': array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])}

every sentence in the data has an un equal length ,truncation will say that every sentence should be  equal to take as max sentence
if
- sen1:hai how are you
- sen2:im good
- sen1:[hai how are you]
- sen2:[ im good pad pad]
- truncate:2

#Exploration about tokenized_data

In [15]:
tokenized_data['input_ids'][0]

array([  101,  2256,  2814,  2180,  1005,  1056,  4965,  2023,  4106,
        1010,  2292,  2894,  1996,  2279,  2028,  2057, 16599,  1012,
         102,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0])

In [16]:
len(tokenized_data['input_ids'][0])

47

In [17]:
dataset['sentence'][0]

"Our friends won't buy this analysis, let alone the next one we propose."

In [19]:
tokens=tokenizer.tokenize(dataset['sentence'][0])
tokens

['our',
 'friends',
 'won',
 "'",
 't',
 'buy',
 'this',
 'analysis',
 ',',
 'let',
 'alone',
 'the',
 'next',
 'one',
 'we',
 'propose',
 '.']

We are not doing preprocessing,but we need to do that

In [20]:
len(tokens)

17

In [21]:
tokenizer.convert_tokens_to_ids(tokens)

[2256,
 2814,
 2180,
 1005,
 1056,
 4965,
 2023,
 4106,
 1010,
 2292,
 2894,
 1996,
 2279,
 2028,
 2057,
 16599,
 1012]

In [23]:
tokenized_data['token_type_ids']
#O means we are passing single sentence
#1 means we are passing two sentence
#2 means we are passing three sentence

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
#Load a BERT tokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

#Example input sentences
sentence1 = "The cat sat on the mat."
sentence2 = "The dog barked loudly."

#Tokenize the input sentences
tokenized_input = tokenizer(sentence1, sentence2, return_tensors="pt", padding=True, truncation=True)

#Access token type IDs
token_type_ids = tokenized_input["token_type_ids"]

print(token_type_ids)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]])


#Explore about attention mask

In [26]:
tokenized_data['attention_mask']

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

In [27]:
tokenized_data['attention_mask'].shape

(8551, 47)

In [28]:
tokenized_data['attention_mask'][0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

19 tokens 17 +['CLS']+['SLP']

#Compile the model

This model is only used for tenorflow

In [29]:
from transformers import TFAutoModelForSequenceClassification
from tensorflow.keras.optimizers import Adam
#Load and compile model
model=TFAutoModelForSequenceClassification.from_pretrained('google-bert/bert-base-cased')
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy')
model.summary()

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  108310272 
                                                                 
 dropout_37 (Dropout)        multiple                  0 (unused)
                                                                 
 classifier (Dense)          multiple                  1538      
                                                                 
Total params: 108311810 (413.18 MB)
Trainable params: 108311810 (413.18 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


#Fit the model

In [34]:
#x=tokenized_data
#y=labels
import numpy as np
labels = np.array(dataset["label"])
model.fit(tokenized_data,labels)

  5/268 [..............................] - ETA: 1:46:56 - loss: 3.9921

KeyboardInterrupt: 

We can do this

In [ ]:

test_sampe=<'sentence'>===>tokenized
model.predict(tokenized)===>probabilities